# Calendar Kiosk Environment Configuration
# Generated by Terraform

# Calendar Dashboard URL
CALENDAR_URL="${calendar_url}"

# Homer Dashboard URL (for swipe navigation)
HOMER_URL="${homer_url}"

# Display rotation (0, 90, 180, 270)
KIOSK_ROTATION="${rotation}"

# Timezone
TZ="${timezone}"
